line-length = 100

[lint]
select = [
    "E", "W", "F", "I", "B", "C4", "UP", "N", "ANN001", "ANN2", "S", "BLE", "A", "ICN",
    "PIE", "SIM", "ERA", "PD", "PLW", "PERF", "RUF", "ARG"
]
ignore = ["W291", "PERF203"]

[lint.isort]
lines-after-imports = 2
force-single-line = true
force-sort-within-sections = true

[lint.pyupgrade]
keep-runtime-typing = true

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"